- name: Start ranger
  service:
    name: ranger
    state: started
    enabled: yes
    daemon_reload: yes

- name: Stop ranger
  service:
    name: ranger
    state: stopped
    enabled: no

- name: Restart ranger
  service:
    name: ranger
    state: restarted
    enabled: yes
